# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'CsvParserApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CsvParserApp
  pod 'R.swift'

  # Pods for CsvParserAppTests
  target 'CsvParserAppTests' do
    inherit! :search_paths
	pod 'Nimble'
	pod 'Quick', '~> 2.0.0'
  end
end
